### ISSUE TITLE
BG info required in context object of search request

### ISSUE THREAD

**Issue by akil4n** [Open-network-for-digital-commerce/ONDC-Protocol-Specs#10]
new field in context object to describe the source of the request origin specially for the search requests. BAP might initiates search directly or through BG but BPP couldn't know 

1. Which entity triggers the request BG / BAP ?
2. if its BG which BG?

similar to `bpp_id` & `bpp_url`,  `bg_id`, `bg_url`  fields would be helpful.
Thanks

**Comment by BLR-0118** [comment]
Search request is always initiated through gateway. If buyer app initiates search, it can lookup gateway from registry and send search to the endpoint. Same for response. Since gateway is stateless, it doesn't matter which gateway initiated search and which sends back the response. How will this help?

**Comment by akil4n** [comment]
understood your point that BG is stateless. If multiple BGs' available in the network, how the BAP/ BPP knows which BG to request / respond ?

**Comment by BLR-0118** [comment]
they can lookup the registry and identify a BG based on their own criteria. For now, closing this. If required, please reopen with appropriate justification.
